# Generated by Django 6.0.3 on 2026-04-09 17:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_alter_class_id_alter_grade_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='qr_code_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='qr_codes'),
        ),
    ]
