# Generated by Django 6.0.2 on 2026-02-20 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.class'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='marked_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to='students.teacher'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='students.student'),
        ),
        migrations.AddField(
            model_name='attendancesubmission',
            name='class_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_submissions', to='students.class'),
        ),
        migrations.AddField(
            model_name='attendancesubmission',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_submissions', to='students.teacher'),
        ),
        migrations.AddField(
            model_name='attendancesummary',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_summaries', to='students.student'),
        ),
        migrations.AddField(
            model_name='flaggedabsence',
            name='followed_up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='followed_up_absences', to='students.teacher'),
        ),
        migrations.AddField(
            model_name='flaggedabsence',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flagged_absences', to='students.student'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['date', 'class_session'], name='attendance__date_0edff5_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['student', 'date'], name='attendance__student_588cfe_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancerecord',
            index=models.Index(fields=['status', 'date'], name='attendance__status_15e5cd_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('student', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancesubmission',
            index=models.Index(fields=['date', 'status'], name='attendance__date_d798fb_idx'),
        ),
        migrations.AddIndex(
            model_name='attendancesubmission',
            index=models.Index(fields=['teacher', 'date'], name='attendance__teacher_30c42b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesubmission',
            unique_together={('teacher', 'class_session', 'date')},
        ),
        migrations.AddIndex(
            model_name='attendancesummary',
            index=models.Index(fields=['student', 'year', 'month'], name='attendance__student_a5697d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attendancesummary',
            unique_together={('student', 'month', 'year')},
        ),
        migrations.AddIndex(
            model_name='flaggedabsence',
            index=models.Index(fields=['is_resolved', 'priority'], name='attendance__is_reso_7eb62f_idx'),
        ),
        migrations.AddIndex(
            model_name='flaggedabsence',
            index=models.Index(fields=['student', 'is_resolved'], name='attendance__student_4cd485_idx'),
        ),
    ]
