# Generated by Django 6.0.2 on 2026-02-23 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_initial'),
        ('students', '0002_grade_term_subject_performancerecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='students.subject'),
        ),
    ]
